### ISSUE TITLE
Validate content-type in the login post handler

### ISSUE THREAD

**Issue by abdavid** [enonic/app-standardidprovider#100]
After I ran a detectify scan on a xp installation running 6.13 - one of the things that came up with a high threat score is that the login implementation seems to be lacking CSRF token on a login form. 

https://support.detectify.com/customer/portal/articles/1969819-login-csrf

**Comment by rymsha** [comment]
There is no need for CSRF token. We can mitigate this by additng a pre check for in post function. 
```
    if (req.headers['Content-Type'] !== 'application/json') {
        return {
            ... fail ...
        }
    }
```

Cross site POST with `application-json` Content-Type requires a preflight request and that will fail as we don't allow CORS.

**Comment by rymsha** [comment]
One more thing: Chromium based browsers are not affected. they do not set a session cookie on CORS requests.
