### ISSUE TITLE
Use the Audit log to track user actions

### ISSUE THREAD

**Issue by jsi** [enonic/app-standardidprovider#179]
This issue will probably touch on several applications, at least this one (app-standardidprovider) and app-users, but it is here for now:

For our ISO 27001 certification, we need to collect much more evidence about what is going on in an XP installation, than we do today.  Especially when it comes to user actions.  This is required by Annex 12.4.1, 12.4.2, and 12.4.3 in the standard.  See also: https://github.com/enonic/iso/issues/219

Now that we have an audit log, we need to create audit logging events for when any principal is created, deleted or updated.

Many customers will use other ID Providers, like LDAP or Auth0, which does this kind of work already, so consider if it should be possible to turn this audit logging on and off.

**Comment by sigdestad** [comment]
These are valid requirements, but we have to do this carefully to avoid flooding audit log.

**Comment by alansemenov** [comment]
We can create a separate issue for tracking logging in/out only in Standard Id provider which will be done with a config switch, but we need to implement Vacuum cleaning of Audit log first.

**Comment by sigdestad** [comment]
We also need to audit app install trails - so should have a session to discuss this alltogether

**Comment by sigdestad** [comment]
I propose we focus on what more we should audit trail automatically, since user login is "debatable" - that can be part of the discussion. Creating a new issue for this which is broader.
